#!/bin/sh

source $HOME/.config/helpers.sh


system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install xcode-select if it's missing
  if ! command -v xcode-select -p >/dev/null 1>&1; then
    echo "Installing xcode-select"
    xcode-select --install
  fi

  # install oh-my-zsh if it's missing
  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi

  echo "Installing oh-my-zsh Powerlevel10k Theme"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.config/oh-my-zsh}/themes/powerlevel10k

  echo "Installing oh-my-zsh plugins"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.config/oh-my-zsh}/plugins/zsh-syntax-highlighting
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.config/oh-my-zsh}/plugins/zsh-autosuggestions
  git clone https://github.com/TamCore/autoupdate-oh-my-zsh-plugins ${ZSH_CUSTOM:-$HOME/.config/oh-my-zsh}/plugins/autoupdate

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # To install useful key bindings and fuzzy completion:
  # $(brew --prefix)/opt/fzf/install

  if [ ! -d "$HOME/.nvm" ]; then
    echo "Installing nvm"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
  fi
fi

# Update the yadm repo origin URL
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:dennzimm/dotfiles.git"

# Set MacOS defaults 
source $HOME/.macos